# Generated by Django 6.0.3 on 2026-03-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('outro', 'Outro')], max_length=10)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('nascimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['nome'],
            },
        ),
    ]
